<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOCzCCOp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOCzCCOp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOCzCCOp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOCzCCOp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOCzCCOp\App_KernelDevDebugContainer([
    'container.build_hash' => 'OCzCCOp',
    'container.build_id' => '80734c62',
    'container.build_time' => 1677101284,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOCzCCOp');
