version: '3.7'
services:
    php:
        container_name: php
        build:
            context: .
        ports:
            - '9000:9000'
        volumes:
            - ./php:/var/www/html
            - ./sys:/
        depends_on:
            - database
        env_file:
            - ./php/.env
        entrypoint: /usr/local/bin/entrypoint.sh

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./php:/var/www/html:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database

    database:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: erp
