version: "3.8"

services:
    db:
        image: mysql
        container_name: erp-db
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
        ports:
            - "3306:3306"
        networks:
            - dev

    app:
        build: php
        container_name: erp-app
        ports:
            - "8000:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./app:/var/www/app
        networks:
            - dev


networks:
    dev:

volumes:
    db-data:

