version: "3.8"

services:
    db:
        image: mysql
        container_name: erp-db
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=db
        networks:
            - dev

    app:
        build: php
        container_name: erp-app
        ports:
            - "8000:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./app:/var/www/app
        networks:
            - dev


networks:
    dev:

volumes:
    db-data:

