version: "3.8"

services:
    db:
        image: mysql
        container_name: erp-db
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
        networks:
            - dev

    app:
        build: php
        container_name: erp-app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./app:/var/www/app
        networks:
            - dev
        env_file:
            - ./app/.env.test


networks:
    dev:

volumes:
    db-data:

