<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEHkCkZ8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEHkCkZ8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEHkCkZ8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEHkCkZ8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEHkCkZ8\App_KernelDevDebugContainer([
    'container.build_hash' => 'EHkCkZ8',
    'container.build_id' => '39af92ea',
    'container.build_time' => 1677014640,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEHkCkZ8');
