<?php

namespace ContainerEHkCkZ8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BjpWMiLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BjpWMiL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BjpWMiL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'registerValidationEmailSenderService' => ['privates', 'App\\Service\\EmailSender\\RegisterValidationEmailSenderService', 'getRegisterValidationEmailSenderServiceService', true],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'verifyEmailHelper' => ['privates', 'symfonycasts.verify_email.helper', 'getSymfonycasts_VerifyEmail_HelperService', true],
        ], [
            'entityManager' => '?',
            'registerValidationEmailSenderService' => 'App\\Service\\EmailSender\\RegisterValidationEmailSenderService',
            'userPasswordHasher' => '?',
            'verifyEmailHelper' => '?',
        ]);
    }
}
