<?php

namespace ContainerEHkCkZ8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterValidationEmailSenderServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EmailSender\RegisterValidationEmailSenderService' shared autowired service.
     *
     * @return \App\Service\EmailSender\RegisterValidationEmailSenderService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EmailSender/EmailSenderService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/EmailSender/RegisterValidationEmailSenderService.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\EmailSender\\RegisterValidationEmailSenderService'])) {
            return $container->privates['App\\Service\\EmailSender\\RegisterValidationEmailSenderService'];
        }

        return $container->privates['App\\Service\\EmailSender\\RegisterValidationEmailSenderService'] = new \App\Service\EmailSender\RegisterValidationEmailSenderService($a, ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))), ($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
