<?php

namespace ContainerOCzCCOp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z1P4fKzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z1P4fKz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z1P4fKz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'resetPasswordEmailSenderService' => ['privates', 'App\\Service\\EmailSender\\ResetPasswordEmailSenderService', 'getResetPasswordEmailSenderServiceService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'resetPasswordEmailSenderService' => 'App\\Service\\EmailSender\\ResetPasswordEmailSenderService',
            'translator' => '?',
        ]);
    }
}
