<?php

namespace ContainerOCzCCOp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNavbarUserSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\NavbarUserSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\NavbarUserSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/NavbarUserSubscriber.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\EventSubscriber\\NavbarUserSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\NavbarUserSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\NavbarUserSubscriber'] = new \App\EventSubscriber\NavbarUserSubscriber($a);
    }
}
