# Configuration file for the AdminLTE bundle
#
# For more information about the bundle settings visit:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/configurations.md
#
# For tabs in the control_sidebar (right screen) add the 'control_sidebar' config key:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/control_sidebar.md

admin_lte:
    options:
        skin: skin-blue-light
        fixed_layout: false
        boxed_layout: false
        collapsed_sidebar: false
        mini_sidebar: true

    knp_menu:
        enable: false

    routes:
        adminlte_welcome: app_index
        adminlte_login: app_login
        adminlte_login_check: app_login
        adminlte_registration: app_register
        adminlte_password_reset: app_forgot_password_request
        adminlte_profile: app_user_profile

        adminlte_notification: app_index
        adminlte_notifications: app_index
        adminlte_task: app_index
        adminlte_tasks: app_index
        adminlte_message: app_index
        adminlte_messages: app_index

